version: "3.7"

services:
  # Node.js web app with hot-reload
  web-app:
    image: web-app-dev:latest
    container_name: web-app-dev
    restart: always
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
      target: runner
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: local.logbook.com
      VIRTUAL_PORT: 8080
    volumes:
      - ./web-app/src:/usr/web-app/src
      - ./web-app/public:/usr/web-app/public

  # Go server with Air for hot-reload
  server:
    image: server-dev:latest
    container_name: server-dev
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      target: runner
    ports:
      - "4000:4000"
    environment:
      VIRTUAL_HOST: local-api.logbook.com
      VIRTUAL_PORT: 8080
    volumes:
      - ./server:/usr/server

  # nginx proxy for local https
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:3000"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
